# Generated by Django 4.1.3 on 2023-05-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asynctask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='async_import_export_task',
            name='process',
            field=models.IntegerField(default=0),
        ),
    ]
