# Generated by Django 4.1.3 on 2023-05-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asynctask', '0002_async_import_export_task_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='async_import_export_task',
            name='ids',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='async_import_export_task',
            name='finish_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='async_import_export_task',
            name='process_time',
            field=models.FloatField(default=0),
        ),
    ]
