# Generated by Django 4.1.3 on 2023-05-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asynctask', '0003_async_import_export_task_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='async_import_export_task',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
