# Generated by Django 4.1.3 on 2023-05-15 05:18

from django.db import migrations, models
import django.db.models.deletion
import utils.utils_time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '__first__'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='类别名')),
                ('type', models.BooleanField(default=False)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department', verbose_name='所属部门')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.entity', verbose_name='所属业务实体')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.assetclass', verbose_name='父级类别')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('life', models.IntegerField(default=0)),
                ('create_time', models.FloatField(default=utils.utils_time.get_timestamp)),
                ('renew_time', models.FloatField(default=utils.utils_time.get_timestamp, null=True)),
                ('description', models.TextField(default='')),
                ('additionalinfo', models.TextField(default='')),
                ('additional', models.TextField(default='{}')),
                ('status', models.IntegerField(choices=[(0, 'Idle'), (1, 'Inuse'), (2, 'Maintain'), (3, 'Clear'), (4, 'Delete'), (5, 'Process')], default=0)),
                ('number', models.IntegerField(default=1, null=True)),
                ('number_idle', models.IntegerField(null=True)),
                ('usage', models.TextField(default='[]')),
                ('maintain', models.TextField(default='[]')),
                ('process', models.TextField(default='[]')),
                ('number_expire', models.IntegerField(default=0)),
                ('expire', models.BooleanField(default=False)),
                ('haspic', models.BooleanField(default=False)),
                ('belonging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belonging', to='user.user')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.assetclass')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.entity')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset.asset')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='user.user')),
            ],
            options={
                'db_table': 'Asset',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=0)),
                ('number', models.FloatField(default=0)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department', verbose_name='所属部门')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.entity', verbose_name='所属业务实体')),
            ],
        ),
    ]
