# Generated by Django 4.0.3 on 2023-04-04 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('user', '0003_delete_sessionpool'),
        ('asset', '0002_alter_asset_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.entity'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='belonging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='类别名')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.assetclass', verbose_name='父级类别')),
            ],
        ),
    ]
