# Generated by Django 4.0.3 on 2023-04-06 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('user', '0003_delete_sessionpool'),
        ('asset', '0003_asset_entity_alter_asset_belonging_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='asset.assetclass'),
        ),
        migrations.AddField(
            model_name='asset',
            name='expire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintain',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='asset',
            name='number_expire',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='number_idle',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='usage',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='user.user'),
        ),
        migrations.AddField(
            model_name='assetclass',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='assetclass',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.entity', verbose_name='所属业务实体'),
        ),
        migrations.AddField(
            model_name='assetclass',
            name='type',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='belonging',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='belonging', to='user.user'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='department.department'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='department.entity'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='asset',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset.asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.IntegerField(choices=[(0, 'Idle'), (1, 'Inuse'), (2, 'Maintain'), (3, 'Clear')], default=0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='assetclass',
            name='name',
            field=models.CharField(max_length=128, verbose_name='类别名'),
        ),
        migrations.AlterField(
            model_name='assetclass',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.assetclass', verbose_name='父级类别'),
        ),
    ]
