# Generated by Django 4.1.3 on 2023-04-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_apps'),
        ('department', '0004_department_attributes'),
        ('asset', '0004_asset_category_asset_expire_asset_maintain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='belonging',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belonging', to='user.user'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.assetclass'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.entity'),
        ),
    ]
