# Generated by Django 4.1.3 on 2023-04-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_alter_asset_belonging_alter_asset_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='process',
            field=models.TextField(default='[]'),
        ),
    ]
