# Generated by Django 4.1.3 on 2023-04-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_asset_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.IntegerField(choices=[(0, 'Idle'), (1, 'Inuse'), (2, 'Maintain'), (3, 'Clear'), (4, 'Delete'), (5, 'Process')], default=0),
        ),
    ]
