# Generated by Django 4.1.3 on 2023-05-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_asset_renew_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='haspic',
            field=models.BooleanField(default=False),
        ),
    ]
