# Generated by Django 4.1.3 on 2023-05-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_asset_haspic'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='additionalinfo',
            field=models.TextField(default=''),
        ),
    ]
