# Generated by Django 4.1.3 on 2023-05-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_asset_additionalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='number',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
