# Generated by Django 4.1.3 on 2023-05-08 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_alter_department_attributes'),
        ('asset', '0011_alter_asset_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department', verbose_name='所属部门')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.entity', verbose_name='所属业务实体')),
            ],
        ),
    ]
