# Generated by Django 4.1.3 on 2023-05-10 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_alter_asset_price'),
        ('asset', '0013_alter_alert_number'),
    ]

    operations = [
    ]
