# 用于CI-CD的持久化的配置文件

# This file is NOT used while deploying to SECODER Platform.
site:
    debug: false
    secret_key: "django-insecure-xvv16d@^4vu6-_^8w73_wt+xqf-wfppqevn)_zgye!#7l^6=p$"
    allowed_hosts: # Backend
    - 'localhost'
    - '127.0.0.1:8000'
    cors_allowed_hosts: # Frontend
    - 'http://localhost:3000'
    - 'https://Aplus-frontend-Aplus.app.secoder.net'

database:
    type: "sqlite3" # Choose between "mysql" and "sqlite3", the latter would lose data after updating
    host: "database.Aplus.secoder.local"
    port: 3306
    name: "AplusBackend"
    user: "root"
    password: "ys"
feishu:
    encrypt_key: "uJHwvC9MR6OL2m2gonsWadkVBdrqF1tN"
    app_id: "cli_a4b17e84d0f8900e"
    app_secret: "bMrD4Rtx85VS0jiPhPgThdrohZTHR4Jo"
    verification_token: "AOKjmM7RLNEw9pPck9zyNcF7KvshqL4F"
frontend: "http://localhost:3000"