# 本地持久化的配置文件，其实就是把数据库改成了sqlite3 

# This file is NOT used while deploying to SECODER Platform.
site:
    debug: false
    secret_key: "django-insecure-xvv16d@^4vu6-_^8w73_wt+xqf-wfppqevn)_zgye!#7l^6=p$"
    allowed_hosts: # Backend
    - '*'
database:
    type: "sqlite3" # Choose between "mysql" and "sqlite3", the latter would lose data after updating
    host: "database.Aplus.secoder.local"
    port: 3306
    name: "AplusBackend"
    user: "root"
    password: "ys"
feishu:
    encrypt_key: "uJHwvC9MR6OL2m2gonsWadkVBdrqF1tN"
    app_id: "cli_a4b17e84d0f8900e"
    app_secret: "bMrD4Rtx85VS0jiPhPgThdrohZTHR4Jo"
    verification_token: "AOKjmM7RLNEw9pPck9zyNcF7KvshqL4F"