# Generated by Django 4.1.3 on 2023-04-19 06:29

from django.db import migrations, models
import django.db.models.deletion
import utils.utils_time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0008_alter_user_apps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feishu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token_create_time', models.FloatField(default=utils.utils_time.get_timestamp)),
                ('access_token', models.TextField()),
                ('access_expires_in', models.PositiveIntegerField()),
                ('refresh_token', models.TextField()),
                ('refresh_expires_in', models.PositiveIntegerField()),
                ('name', models.TextField()),
                ('open_id', models.TextField()),
                ('union_id', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
