# Generated by Django 4.1.3 on 2023-05-15 05:19

from django.db import migrations, models
import django.db.models.deletion
import utils.utils_time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('eventid', models.CharField(max_length=255, verbose_name='事件唯一标识')),
                ('eventtype', models.CharField(default='', max_length=255, verbose_name='事件类型')),
                ('create_time', models.BigIntegerField(default=utils.utils_time.get_timestamp, verbose_name='创建时间')),
                ('create_time_format', models.CharField(default=utils.utils_time.get_time, max_length=255, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'Event',
            },
        ),
        migrations.CreateModel(
            name='Feishu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token_create_time', models.FloatField(default=utils.utils_time.get_timestamp)),
                ('access_token', models.TextField(default='')),
                ('access_expires_in', models.PositiveIntegerField(default=0)),
                ('refresh_token', models.TextField(default='')),
                ('refresh_expires_in', models.PositiveIntegerField(default=0)),
                ('name', models.TextField()),
                ('userid', models.TextField(default='')),
                ('openid', models.TextField(default='')),
                ('unionid', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feishu', to='user.user')),
            ],
            options={
                'db_table': 'feishu',
            },
        ),
        migrations.CreateModel(
            name='EventException',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('msg', models.TextField(verbose_name='报错信息')),
                ('event', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='feishu.event')),
            ],
            options={
                'db_table': 'EventException',
            },
        ),
    ]
