# Generated by Django 4.1.3 on 2023-04-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feishu', '0002_event_rename_open_id_feishu_unionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feishu',
            name='access_expires_in',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feishu',
            name='access_token',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='feishu',
            name='refresh_expires_in',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feishu',
            name='refresh_token',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='EventException',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('msg', models.TextField(verbose_name='报错信息')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feishu.event')),
            ],
        ),
    ]
