# Generated by Django 4.1.3 on 2023-04-21 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feishu', '0002_event_rename_open_id_feishu_unionid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_id',
            new_name='eventid',
        ),
    ]
