# Generated by Django 4.1.3 on 2023-04-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feishu', '0003_alter_feishu_access_expires_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventtype',
            field=models.CharField(default='', max_length=255, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventid',
            field=models.CharField(max_length=255, verbose_name='事件唯一标识'),
        ),
        migrations.AlterModelTable(
            name='event',
            table='Event',
        ),
        migrations.AlterModelTable(
            name='eventexception',
            table='EventException',
        ),
        migrations.AlterModelTable(
            name='feishu',
            table='FeishuUser',
        ),
    ]
