# Generated by Django 4.1.3 on 2023-04-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feishu', '0004_event_eventtype_alter_event_eventid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='create_time_format',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
