# Generated by Django 4.1.3 on 2023-04-25 08:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_apps'),
        ('feishu', '0005_event_create_time_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='create_time_format',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='feishu',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feishu', to='user.user'),
        ),
    ]
