# Generated by Django 4.1.3 on 2023-04-25 09:26

from django.db import migrations, models
import utils.utils_time


class Migration(migrations.Migration):

    dependencies = [
        ('feishu', '0006_alter_event_create_time_format_alter_feishu_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='create_time_format',
            field=models.CharField(default=utils.utils_time.get_time, max_length=255, verbose_name='创建时间'),
        ),
    ]
