# Generated by Django 4.1.3 on 2023-04-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feishu', '0007_alter_event_create_time_format'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feishu',
            table='feishu',
        ),
    ]
