# Generated by Django 4.1.3 on 2023-04-25 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feishu', '0008_alter_feishu_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventexception',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='feishu.event'),
        ),
    ]
