# Generated by Django 4.1.3 on 2023-05-15 05:18

from django.db import migrations, models
import django.db.models.deletion
import utils.utils_time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accessTimeOutLogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('re_time', models.CharField(max_length=255, verbose_name='请求时间')),
                ('re_url', models.TextField(verbose_name='请求url')),
                ('re_method', models.CharField(max_length=20, verbose_name='请求方法')),
                ('re_ip', models.CharField(max_length=32, verbose_name='请求IP')),
                ('re_content', models.TextField(null=True, verbose_name='请求参数')),
                ('rp_content', models.TextField(null=True, verbose_name='响应内容')),
                ('access_time', models.FloatField(verbose_name='耗时/ms')),
            ],
            options={
                'db_table': 'accessTimeOutLogs',
            },
        ),
        migrations.CreateModel(
            name='httpLogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('re_time', models.CharField(max_length=255, verbose_name='请求时间')),
                ('re_url', models.TextField(verbose_name='请求url')),
                ('re_method', models.CharField(max_length=20, verbose_name='请求方法')),
                ('re_ip', models.CharField(max_length=32, verbose_name='请求IP')),
                ('re_content', models.TextField(null=True, verbose_name='请求参数')),
                ('rp_content', models.TextField(null=True, verbose_name='响应内容')),
                ('access_time', models.FloatField(verbose_name='耗时/ms')),
            ],
            options={
                'db_table': 'httpLogs',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity', models.BigIntegerField(default=0)),
                ('content', models.TextField(default='{}')),
                ('time', models.FloatField(default=utils.utils_time.get_timestamp)),
                ('type', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='AssetLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity', models.BigIntegerField(default=0)),
                ('department', models.BigIntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('number', models.IntegerField(default=1)),
                ('time', models.FloatField(default=utils.utils_time.get_timestamp)),
                ('expire_time', models.FloatField(default=0)),
                ('life', models.IntegerField(default=0)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
                ('dest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dest', to='user.user')),
                ('src', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='src', to='user.user')),
            ],
            options={
                'db_table': 'AssetLog',
                'managed': True,
            },
        ),
    ]
