# Generated by Django 4.1.3 on 2023-04-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_logs_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='accessTimeOutLogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('re_time', models.CharField(max_length=255, verbose_name='请求时间')),
                ('re_url', models.TextField(verbose_name='请求url')),
                ('re_method', models.CharField(max_length=20, verbose_name='请求方法')),
                ('re_ip', models.CharField(max_length=32, verbose_name='请求IP')),
                ('re_content', models.TextField(verbose_name='请求参数')),
                ('rp_content', models.TextField(verbose_name='响应内容')),
                ('access_time', models.FloatField(verbose_name='耗时/ms')),
            ],
            options={
                'db_table': 'accessTimeOutLogs',
            },
        ),
        migrations.CreateModel(
            name='httpLogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('re_time', models.CharField(max_length=255, verbose_name='请求时间')),
                ('re_url', models.TextField(verbose_name='请求url')),
                ('re_method', models.CharField(max_length=20, verbose_name='请求方法')),
                ('re_ip', models.CharField(max_length=32, verbose_name='请求IP')),
                ('re_content', models.TextField(null=True, verbose_name='请求参数')),
                ('rp_content', models.TextField(null=True, verbose_name='响应内容')),
                ('access_time', models.FloatField(verbose_name='耗时/ms')),
            ],
            options={
                'db_table': 'httpLogs',
            },
        ),
    ]
