# Generated by Django 4.1.3 on 2023-05-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_accesstimeoutlogs_httplogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstimeoutlogs',
            name='re_content',
            field=models.TextField(null=True, verbose_name='请求参数'),
        ),
        migrations.AlterField(
            model_name='accesstimeoutlogs',
            name='rp_content',
            field=models.TextField(null=True, verbose_name='响应内容'),
        ),
    ]
