# Generated by Django 4.1.3 on 2023-05-07 12:51

from django.db import migrations, models
import django.db.models.deletion
import utils.utils_time


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_apps'),
        ('asset', '0011_alter_asset_number'),
        ('logs', '0003_accesstimeoutlogs_httplogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity', models.BigIntegerField(default=0)),
                ('department', models.BigIntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('number', models.IntegerField(default=1)),
                ('time', models.FloatField(default=utils.utils_time.get_timestamp)),
                ('expire_time', models.FloatField(default=0)),
                ('life', models.IntegerField(default=0)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
                ('dest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dest', to='user.user')),
                ('src', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='src', to='user.user')),
            ],
            options={
                'db_table': 'AssetLog',
                'managed': True,
            },
        ),
    ]
