# Generated by Django 4.1.3 on 2023-05-10 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_accesstimeoutlogs_re_content_and_more'),
        ('logs', '0004_assetlog'),
    ]

    operations = [
    ]
