# Generated by Django 4.1.3 on 2023-05-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_assetlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlog',
            name='expire_time',
            field=models.FloatField(default=0),
        ),
    ]
