# Generated by Django 4.1.3 on 2023-05-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_assetlog_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlog',
            name='life',
            field=models.IntegerField(default=0),
        ),
    ]
