# Generated by Django 4.1.3 on 2023-05-15 05:18

from django.db import migrations, models
import django.db.models.deletion
import utils.utils_time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.BigIntegerField(default=0)),
                ('pending', models.BigIntegerField(default=0)),
                ('type', models.BigIntegerField(default=0)),
                ('content', models.TextField(default='')),
                ('read', models.BooleanField(default=False)),
                ('time', models.FloatField(default=utils.utils_time.get_timestamp)),
            ],
            options={
                'db_table': 'Message',
            },
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity', models.BigIntegerField(default=0)),
                ('department', models.BigIntegerField(default=0)),
                ('initiator', models.BigIntegerField(default=0)),
                ('destination', models.BigIntegerField(default=0)),
                ('asset', models.TextField(default='[]')),
                ('type', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=100)),
                ('reply', models.CharField(default='', max_length=100)),
                ('result', models.IntegerField(default=0)),
                ('request_time', models.FloatField(default=utils.utils_time.get_timestamp)),
                ('review_time', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'Pending',
            },
        ),
        migrations.CreateModel(
            name='EPMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.BigIntegerField(default=0)),
                ('type', models.IntegerField()),
                ('content', models.TextField(default='')),
                ('aware', models.BigIntegerField(default=0)),
                ('time', models.FloatField(default=utils.utils_time.get_timestamp)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
            ],
        ),
    ]
