# Generated by Django 4.1.7 on 2023-04-01 07:20

from django.db import migrations, models
import utils.utils_time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department', models.BigIntegerField()),
                ('initiator', models.BigIntegerField()),
                ('destination', models.BigIntegerField(default=0)),
                ('asset', models.BigIntegerField()),
                ('type', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=100)),
                ('reply', models.CharField(default='', max_length=100)),
                ('result', models.IntegerField(default=0)),
                ('request_time', models.BigIntegerField(default=utils.utils_time.get_timestamp)),
                ('review_time', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'Pending',
            },
        ),
    ]
