# Generated by Django 4.1.3 on 2023-04-03 09:44

from django.db import migrations, models
import utils.utils_time


class Migration(migrations.Migration):

    dependencies = [
        ('pending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='request_time',
            field=models.FloatField(default=utils.utils_time.get_timestamp),
        ),
        migrations.AlterField(
            model_name='pending',
            name='review_time',
            field=models.FloatField(default=0),
        ),
    ]
