# Generated by Django 4.1.3 on 2023-04-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pending', '0002_alter_pending_request_time_alter_pending_review_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='asset',
            field=models.TextField(default=''),
        ),
    ]
