# Generated by Django 4.1.3 on 2023-04-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pending', '0004_alter_pending_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='entity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pending',
            name='department',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pending',
            name='initiator',
            field=models.BigIntegerField(default=0),
        ),
    ]
