# Generated by Django 4.1.3 on 2023-04-23 04:52

from django.db import migrations, models
import utils.utils_time


class Migration(migrations.Migration):

    dependencies = [
        ('pending', '0005_pending_entity_alter_pending_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.BigIntegerField(default=0)),
                ('content', models.TextField(default='')),
                ('read', models.BooleanField(default=False)),
                ('time', models.FloatField(default=utils.utils_time.get_timestamp)),
            ],
            options={
                'db_table': 'Message',
            },
        ),
    ]
