# Generated by Django 4.1.3 on 2023-04-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pending', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pending',
            field=models.BigIntegerField(default=0),
        ),
    ]
