# Generated by Django 4.1.3 on 2023-04-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pending', '0007_message_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.BigIntegerField(default=0),
        ),
    ]
