# Generated by Django 4.1.3 on 2023-05-08 11:09

from django.db import migrations, models
import django.db.models.deletion
import utils.utils_time


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_alter_alert_number'),
        ('pending', '0008_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.BigIntegerField(default=0)),
                ('type', models.IntegerField()),
                ('content', models.TextField(default='')),
                ('time', models.FloatField(default=utils.utils_time.get_timestamp)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
            ],
        ),
    ]
