# Generated by Django 4.1.3 on 2023-05-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pending', '0009_epmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='epmessage',
            name='aware',
            field=models.BigIntegerField(default=0),
        ),
    ]
