# Generated by Django 4.1.7 on 2023-04-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_sessionpool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionPool',
        ),
    ]
