# Generated by Django 4.1.3 on 2023-04-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_sessionpool'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='label',
            field=models.TextField(default='name,entity,department'),
        ),
    ]
