# Generated by Django 4.1.3 on 2023-04-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='label',
        ),
    ]
