# Generated by Django 4.1.3 on 2023-04-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apps',
            field=models.TextField(default=''),
        ),
    ]
