# Generated by Django 4.1.3 on 2023-04-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_apps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apps',
            field=models.TextField(default='{"data":{}}'),
        ),
    ]
