# Generated by Django 4.1.3 on 2023-05-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hasasset',
            field=models.IntegerField(default=0),
        ),
    ]
