# Generated by Django 4.1.7 on 2023-04-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('entity', models.BigIntegerField()),
                ('parent', models.BigIntegerField(default=0)),
                ('admin', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('admin', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'Entity',
            },
        ),
    ]
