# Generated by Django 4.1.3 on 2023-04-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='attributes',
            field=models.TextField(default='{}'),
        ),
    ]
