# Generated by Django 4.1.3 on 2023-04-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_department_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='attributes',
            field=models.TextField(default=''),
        ),
    ]
