# Generated by Django 4.1.3 on 2023-05-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_alter_department_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='attributes',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='department',
            name='label',
            field=models.TextField(default='[]'),
        ),
    ]
